version: '3.9'

volumes:
  palworld-server-files:


services:
  server-files:
    image: steamcmd/steamcmd:ubuntu
    volumes:
      - palworld-server-files:/server-files/
    entrypoint: [ '/bin/bash', '-ec' ]
    command:
      - |
        # Install & update official server files
        steamcmd_cmd=(
          steamcmd
          +force_install_dir /server-files/
          +login anonymous
          +app_update 2394010 validate
          +quit
        )
        "$${steamcmd_cmd[@]}"

  palworld-server:
    build:
      context: .
      args:
        server_port: $SERVER_PORT
        user_id: $SERVER_USER_ID
        user_name: $SERVER_USER_NAME
        group_id: $SERVER_GROUP_ID
        group_name: $SERVER_GROUP_NAME

    image: palworld-server:1.0
    container_name: palworld-server
    entrypoint: [ '/server-files/server/start.sh' ]
    ports:
      - $SERVER_PORT:$SERVER_PORT/udp
    user: "$SERVER_USER_NAME:$SERVER_GROUP_NAME"
    volumes:
      - palworld-server-files:/server-files/

  cmd:
    extends: palworld-server
    entrypoint: [ '/bin/bash', '-ec' ]

  backup:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add --no-cache tzdata
        RUN ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
    entrypoint: [ '/bin/sh', '-ec' ]
    volumes:
      - palworld-server-files:/server-files/
      - ../backups:/backups
    command:
      - |
        server_data_path="/server-files/Pal/Saved"
        timestamp=$(date +%y-%m-%d-%H-%M-%S)
        backup_path="/backups/backup-$$timestamp.tar.bz2"
        # Backup server files using bzip2
        tar -cjf "$$backup_path" -C "$$server_data_path" .
