version: '3.9'

volumes:
  palworld-server-files:


services:
  server-files:
    image: steamcmd/steamcmd:ubuntu
    volumes:
      - palworld-server-files:/server-files/
    entrypoint: [ '/bin/bash', '-ec' ]
    command:
      - |
        # Install & update official server files
        steamcmd_cmd=(
          steamcmd
          +force_install_dir /server-files/
          +login anonymous
          +app_update 2394010 validate
          +quit
        )
        "$${steamcmd_cmd[@]}"

  palworld-server:
    build:
      context: .
      args:
        server_port: $SERVER_PORT
        rcon_port: $RCON_PORT
        user_id: $SERVER_USER_ID
        user_name: $SERVER_USER_NAME
        group_id: $SERVER_GROUP_ID
        group_name: $SERVER_GROUP_NAME

    image: palworld-server:1.0
    container_name: palworld-server
    entrypoint: [ '/server-files/server/start.sh' ]
    ports:
      - $SERVER_PORT:$SERVER_PORT/udp
      - $RCON_PORT:$RCON_PORT/tcp
    user: "$SERVER_USER_NAME:$SERVER_GROUP_NAME"
    volumes:
      - palworld-server-files:/server-files/

  cmd:
    extends: palworld-server
    entrypoint: [ '/bin/bash', '-ec' ]

  backup:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:latest
        ENV TZ=America/Los_Angeles
        RUN apk add --no-cache tzdata \
         && ln -s /usr/share/zoneinfo/$$TZ /etc/localtime
        RUN addgroup --gid $SERVER_GROUP_ID $SERVER_GROUP_NAME \
         && adduser --disabled-password --gecos "" --uid $SERVER_USER_ID --ingroup $SERVER_GROUP_NAME $SERVER_USER_NAME
    entrypoint: [ '/bin/sh', '-ec' ]
    user: "$SERVER_USER_NAME:$SERVER_GROUP_NAME"
    volumes:
      - palworld-server-files:/server-files/
      - ../backups:/backups
    working_dir: /home/$SERVER_USER_NAME
    command:
      - |
        server_data_path="/server-files/Pal/Saved"
        timestamp=$(date +%Y%j-%H%M%S)
        backup_path="/backups/backup-$$timestamp.tar.bz2"
        # Backup server files using bzip2
        tar -cjf backup.tar.bz2 -C "$$server_data_path" .
        mv backup.tar.bz2 "$$backup_path"
