# References:
# - https://develop.nginxproxymanager.com/guide
# - https://hub.docker.com/r/jc21/nginx-proxy-manager

name: $PROJECT_NAME

services:
  gateway:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      TZ: "America/Los_Angeles"
      PUID: $USER_ID
      PGID: $GROUP_ID
    ports:
      - '$GW_PORT_ADMIN:81'
      - '$GW_PORT_HTTP:80'
      - '$GW_PORT_HTTPS:443'
    volumes:
      - data:/data
      - cert:/etc/letsencrypt

volumes:
  data:
  cert:
