name: $SERVER_NAME

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        server_port: $SERVER_PORT
        rcon_port: $RCON_PORT
        user_id: $SERVER_USER_ID
        user_name: $SERVER_USER_NAME
        group_id: $SERVER_GROUP_ID
        group_name: $SERVER_GROUP_NAME
    image: $COMPOSE_PROJECT_NAME-server:1.0
    user: "$SERVER_USER_NAME:$SERVER_GROUP_NAME"

  server:
    depends_on: [ base ]
    image: $COMPOSE_PROJECT_NAME-server:1.0
    container_name: $COMPOSE_PROJECT_NAME-server
    entrypoint: [ '/server-files/server/start.sh' ]
    ports:
      # - $SERVER_PORT:$SERVER_PORT/tcp
      - $SERVER_PORT:$SERVER_PORT/udp
      - $RCON_PORT:$RCON_PORT/tcp
    volumes:
      - ../server-files/:/server-files/

  cmd:
    extends: server
    container_name: $COMPOSE_PROJECT_NAME-cmd
    entrypoint: [ '/bin/bash', '-ec' ]
